### ISSUE TITLE
DB Error after update to 2.1

### ISSUE THREAD

**Issue by eighty20results** [strangerstudios/paid-memberships-pro#1106]
**Describe the bug**
After completing the update to v2.1 and whenever I go to the Membership Dashboard page, I get the following DB error:

```
WordPress database error Incorrect DATETIME value: '' for query SELECT total, COUNT(*) as num FROM wp_pmpro_membership_orders WHERE total > 0 AND status NOT IN('refunded', 'review', 'token', 'error') AND timestamp >= '' AND gateway_environment = 'sandbox'  GROUP BY total ORDER BY num DESC  made by do_action('toplevel_page_pmpro-dashboard'), WP_Hook->do_action, WP_Hook->apply_filters, pmpro_dashboard, require_once('/plugins/paid-memberships-pro/adminpages/dashboard.php'), do_meta_boxes, pmpro_report_sales_widget, pmpro_get_prices_paid
[15-Sep-2019 17:26:59 UTC] WordPress database error Incorrect DATETIME value: '' for query SELECT COUNT(*) FROM wp_pmpro_membership_orders WHERE total > 0 AND status NOT IN('refunded', 'review', 'token', 'error') AND timestamp >= '' AND gateway_environment = 'sandbox'  made by do_action('toplevel_page_pmpro-dashboard'), WP_Hook->do_action, WP_Hook->apply_filters, pmpro_dashboard, require_once('/plugins/paid-memberships-pro/adminpages/dashboard.php'), do_meta_boxes, pmpro_report_sales_widget, pmpro_getSales
[15-Sep-2019 17:26:59 UTC] WordPress database error Incorrect DATETIME value: '' for query SELECT SUM(total) FROM wp_pmpro_membership_orders WHERE status NOT IN('refunded', 'review', 'token', 'error') AND timestamp >= '' AND gateway_environment = 'sandbox'  made by do_action('toplevel_page_pmpro-dashboard'), WP_Hook->do_action, WP_Hook->apply_filters, pmpro_dashboard, require_once('/plugins/paid-memberships-pro/adminpages/dashboard.php'), do_meta_boxes, pmpro_report_sales_widget, pmpro_getRevenue
[15-Sep-2019 17:26:59 UTC] WordPress database error Incorrect DATETIME value: '' for query SELECT total, COUNT(*) as num FROM wp_pmpro_membership_orders WHERE total > 0 AND status NOT IN('refunded', 'review', 'token', 'error') AND timestamp >= '' AND gateway_environment = 'sandbox'  GROUP BY total ORDER BY num DESC  made by do_action('toplevel_page_pmpro-dashboard'), WP_Hook->do_action, WP_Hook->apply_filters, pmpro_dashboard, require_once('/plugins/paid-memberships-pro/adminpages/dashboard.php'), do_meta_boxes, pmpro_report_sales_widget, pmpro_get_prices_paid
[15-Sep-2019 17:27:06 UTC] WordPress database error Incorrect DATETIME value: '' for query SELECT COUNT(DISTINCT mu.user_id) FROM wp_pmpro_memberships_users mu WHERE mu.startdate >= ''  made by do_action('toplevel_page_pmpro-dashboard'), WP_Hook->do_action, WP_Hook->apply_filters, pmpro_dashboard, require_once('/plugins/paid-memberships-pro/adminpages/dashboard.php'), do_meta_boxes, pmpro_report_memberships_widget, pmpro_getSignups
[15-Sep-2019 17:27:06 UTC] WordPress database error Incorrect DATETIME value: '' for query SELECT COUNT(DISTINCT mu.user_id) FROM wp_pmpro_memberships_users mu WHERE mu.startdate >= '' AND mu.membership_id IN(1)  made by do_action('toplevel_page_pmpro-dashboard'), WP_Hook->do_action, WP_Hook->apply_filters, pmpro_dashboard, require_once('/plugins/paid-memberships-pro/adminpages/dashboard.php'), do_meta_boxes, pmpro_report_memberships_widget, pmpro_getSignups
[15-Sep-2019 17:27:06 UTC] WordPress database error Incorrect DATETIME value: '' for query SELECT COUNT(DISTINCT mu.user_id) FROM wp_pmpro_memberships_users mu WHERE mu.startdate >= '' AND mu.membership_id IN(2)  made by do_action('toplevel_page_pmpro-dashboard'), WP_Hook->do_action, WP_Hook->apply_filters, pmpro_dashboard, require_once('/plugins/paid-memberships-pro/adminpages/dashboard.php'), do_meta_boxes, pmpro_report_memberships_widget, pmpro_getSignups
```
**To Reproduce**
Update Paid Memberships Pro from v2.0.7 to v2.1
Go to wp-admin -> "Memberships" -> "Dashboard"

**Expected behavior**
No DB errors in error log (i.e. better error checking when generating SQL queries).

**Isolating the problem (mark completed items with an [x]):**
- [ N/A ] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active. 
- [ N/A ] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [ X ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Please share non-sensitive information about your hosting environment such as WordPress version, PHP version, Paid Memberships Pro and any related plugins versions.

WP 5.2.1
PHP 7.2
PMPro v2.1

```
</details>

**Comment by ideadude** [comment]
Thanks for the heads up.

It seems only certain versions of PHP and/or MySQL are throwing this, but we should fix it.

When no period is passed to the functions to generate reports, we set the startdate to '' to get all data. '' is not a DATETIME value. We can either use something like 1970-01-01 as the startdate or update our SQL query construction to check if startdate is empty and if so not include that check in the SQL.

I'm leaning toward the latter. It's a bit more clear if more complicated in code and will probably result in a faster query.

**Comment by matepaiva** [comment]
Hi guys, I got the same problem when I try to access `/wp-admin/admin.php?page=pmpro-dashboard`. This is causing a 512 error and I just can't access the pmpro area. Do you have any workaround for this error?

**Comment by andrewlimaza** [comment]
Looking into this further, it seems there's a typo in the default date for "ALL". It should be 1970-01-01 instead of 1960-01-01.

Here's an example to reference: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/adminpages/reports/memberships.php#L200

**Comment by matepaiva** [comment]
It does not fix the issue. The problem remains on line `523` of `sales.php`, where `$startdate = '';`. To fix that, you must replace the line with `$startdate = '1970-01-01';`.

**Comment by lucasacchiricciardi** [comment]
The issue is back.  On my site I got the same error today 2021-02-18.

As You can see on https://plugintests.com/plugins/wporg/paid-memberships-pro/latest they got the same issue:

[03-Feb-2021 23:35:16 UTC] WordPress database error Incorrect DATETIME value: '' for query SELECT COUNT(*) FROM wp_pmpro_membership_orders WHERE total > 0 AND status NOT IN('refunded', 'review', 'token', 'error') AND timestamp >= '' AND gateway_environment = 'sandbox'  made by do_action('toplevel_page_pmpro-dashboard'), WP_Hook->do_action, WP_Hook->apply_filters, pmpro_dashboard, require_once('/plugins/paid-memberships-pro/adminpages/dashboard.php'), do_meta_boxes, pmpro_report_sales_widget, pmpro_getSales
[03-Feb-2021 23:35:16 UTC] WordPress database error Incorrect DATETIME value: '' for query SELECT SUM(total) FROM wp_pmpro_membership_orders WHERE status NOT IN('refunded', 'review', 'token', 'error') AND timestamp >= '' AND gateway_environment = 'sandbox'  made by do_action('toplevel_page_pmpro-dashboard'), WP_Hook->do_action, WP_Hook->apply_filters, pmpro_dashboard, require_once('/plugins/paid-memberships-pro/adminpages/dashboard.php'), do_meta_boxes, pmpro_report_sales_widget, pmpro_getRevenue
[03-Feb-2021 23:35:18 UTC] WordPress database error Incorrect DATETIME value: '' for query SELECT COUNT(*) FROM wp_pmpro_membership_orders WHERE total > 0 AND status NOT IN('refunded', 'review', 'token', 'error') AND timestamp >= '' AND gateway_environment = 'sandbox'  made by do_action('toplevel_page_pmpro-dashboard'), WP_Hook->do_action, WP_Hook->apply_filters, pmpro_dashboard, require_once('/plugins/paid-memberships-pro/adminpages/dashboard.php'), do_meta_boxes, pmpro_report_sales_widget, pmpro_getSales
[03-Feb-2021 23:35:18 UTC] WordPress database error Incorrect DATETIME value: '' for query SELECT SUM(total) FROM wp_pmpro_membership_orders WHERE status NOT IN('refunded', 'review', 'token', 'error') AND timestamp >= '' AND gateway_environment = 'sandbox'  made by do_action('toplevel_page_pmpro-dashboard'), WP_Hook->do_action, WP_Hook->apply_filters, pmpro_dashboard, require_once('/plugins/paid-memberships-pro/adminpages/dashboard.php'), do_meta_boxes, pmpro_report_sales_widget, pmpro_getRevenue
[03-Feb-2021 23:35:20 UTC] WordPress database error Incorrect DATETIME value: '' for query SELECT COUNT(*) FROM wp_pmpro_membership_orders WHERE total > 0 AND status NOT IN('refunded', 'review', 'token', 'error') AND timestamp >= '' AND gateway_environment = 'sandbox'  made by do_action('memberships_page_pmpro-reports'), WP_Hook->do_action, WP_Hook->apply_filters, pmpro_reports, require_once('/plugins/paid-memberships-pro/adminpages/reports.php'), do_meta_boxes, pmpro_report_sales_widget, pmpro_getSales
[03-Feb-2021 23:35:20 UTC] WordPress database error Incorrect DATETIME value: '' for query SELECT SUM(total) FROM wp_pmpro_membership_orders WHERE status NOT IN('refunded', 'review', 'token', 'error') AND timestamp >= '' AND gateway_environment = 'sandbox'  made by do_action('memberships_page_pmpro-reports'), WP_Hook->do_action, WP_Hook->apply_filters, pmpro_reports, require_once('/plugins/paid-memberships-pro/adminpages/reports.php'), do_meta_boxes, pmpro_report_sales_widget, pmpro_getRevenue
